version: '3.7'

services:
    jvm-info:
      image: cnj/openjdk-jvm-info
      ports:
        - "8080:8080"
      environment:
        JAVA_OPTS: >
          -XX:+PrintFlagsFinal
          -XX:+PrintGCDetails
      deploy:
        resources:
          limits:
            memory: 1024M # dovrebbe essere il doppio della Xmx
            cpus: '3'