version: '3.7'

services:
    jvm-info:
      image: cnj/fabric8-jvm-info
      ports:
        - "8081:8080"
      environment:
        JAVA_OPTIONS: >
          -XX:+PrintFlagsFinal
          -XX:+PrintGCDetails
        JAVA_MAX_CORE: 3
      deploy:
        resources:
          limits:
            cpus: '3'