version: '3.7'

services:
    jvm-info:
      image: cnj/fabric8-jvm-info
      ports:
        - "8081:8080"
      environment:
        # https://blogs.oracle.com/java-platform-group/java-se-support-for-docker-cpu-and-memory-limits
        # https://developers.redhat.com/blog/2017/04/04/openjdk-and-containers/
        # https://www.slideshare.net/RedHatDevelopers/why-youre-going-to-fail-running-java-on-docker
        # https://developers.redhat.com/blog/2017/03/14/java-inside-docker/
        # -XX:+UseSerialGC se cpu=1
          # -Xms512m
          # -Xmx512m
        JAVA_OPTIONS: >
          -XX:+PrintFlagsFinal
          -XX:+PrintGCDetails
        JAVA_MAX_CORE: 2
        JAVA_MAX_MEM_RATIO: 50
        JAVA_INIT_MEM_RATIO: 50
      deploy:
        resources:
          limits:
            memory: 1024M # dovrebbe essere il doppio della Xmx
            cpus: '2'